baseurl: /
title: LuoSongtao-学习笔记
description: "千里之行始于足下；不积跬步无以致千里"
author:
  name: "LuoSongtao"
  email: "ryomawithlst@gmail.com"
  url: ""

source: .
destination: ./docs
permalink: /:categories/:title

pagination:
  enabled: true
  debug: true
  per_page: 5
  permalink: '/page/:num/'
  category: "posts"
  sort_reverse: true
  trail:
    before: 2
    after: 2

defaults:
  -
    scope:
      path: "notes"
      type: "posts"
    values:
      layout: "post"

future: true
plugins: ['jekyll-seo-tag', 'jekyll-paginate-v2', 'jekyll-sitemap' ,'jekyll-toc']

github:
  repository_url: luo-songtao
repository: luo-songtao

search_engine: "js"

# Custom variables
owner : "LuoSongtao"
year : "2019"