version: '3.7'
services:
  build-website:
    build: .
    image: jekyll-build
    ports:
     - 8999:4000
     - 35729:35729
    volumes:
     - .:/srv/jekyll
    command: bundle exec jekyll serve --host 0.0.0.0