name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1.0.5
    - name: Deploy Html To Branch "gh-pages"
      run: |
        git config user.name "luo-songtao"
        git config user.email "ryomawithlst@gmail.com"
        docker-compose build
        docker run --rm --privileged -v `pwd`:/srv/jekyll jekyll-build bundle exec jekyll clean
        t git subtree add --prefix=docs origin gh-pages
        rm -rf docs/*
        chmod 777 docs
        docker run --rm --privileged -v `pwd`:/srv/jekyll jekyll-build bundle exec jekyll build
        git add docs
        git commit -m "${{ github.sha }}"
        git subtree push --prefix=docs origin gh-pages